import json
import os
from pathlib import Path

# Path to all parameters (only this line should be edited)
PARAM_FILE = "data/parameters/test.json"

# Load parameters ######################################################################################################

with open(PARAM_FILE, "r") as f:
    params = json.load(f)

SRC_DIR = Path(params["src_root"])
DST_DIR = Path(params["dst_root"]) / params["name"]

if not DST_DIR.exists():
    os.makedirs(DST_DIR)

# List all data (dataset specific) #####################################################################################

def get_all_data_list():
    """ Root method """

    if params["dataset"] == "sample":
        return get_all_data_list_sample()

    else:
        raise ValueError(f"Unknown dataset {params['dataset']}")

def get_all_data_list_sample():
    """ Single 'sample_raw.fif' file. For debugging"""
    return [SRC_DIR / "sample_raw.fif"]


all_data = get_all_data_list()

# Set targets ##########################################################################################################

# Set targets
target = []

if params["target"] == "filtered_raw":
    target = expand(DST_DIR / "sppas_ipu_csv" / "{sample}.csv", sample=all_data)

# Set rules ############################################################################################################

rule all:
    input:
        target

